language: cpp
cache:
    apt
addon:
    apt:
        sources:
            - ppa:ubuntu-sdk-team/ppa
        packages:
            - qtbase5-dev
compiler:
  - gcc
script:
  - cd semester3/maxflow
  - qmake -qt=qt5
  - make
