######################################################################
# Automatically generated by qmake (3.0) ?? ???. 16 09:46:08 2015
######################################################################

TEMPLATE = app
TARGET = bin/maxflow
INCLUDEPATH += .
QT += widgets 

# Input
SOURCES += graph.cpp main.cpp
HEADERS += graph.h
