######################################################################
# Automatically generated by qmake (3.0) ?? ???. 16 09:46:08 2015
######################################################################

TEMPLATE = app
TARGET = bin/maxflow
INCLUDEPATH += .
QT += widgets
CONFIG += c++11 c++14

# Input
SOURCES += graph.cpp main.cpp log.cpp visualization.cpp
HEADERS += graph.h log.h action.h visualization.h
