bin/main : main.cpp matcher.h matcher.cpp aho.h aho.cpp
	mkdir -p bin/
	g++ -o bin/main -std=c++11 -g main.cpp matcher.cpp aho.cpp
bin/ejudge : ejudge.cpp
	mkdir -p bin/
	g++ -o bin/ejudge -std=c++03 ejudge.cpp
